---
# tasks file for cpu_management
- name: Backup GRUB configuration
  ansible.builtin.copy:
    src: /etc/default/grub
    dest: /etc/default/grub.bak
    owner: root
    group: root
    mode: '0644'
    remote_src: true

- name: Disable C-state for CPUs
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash intel_pstate=disable processor.max_cstate=1 intel_idle.max_cstate=0 idle=poll"'
    state: present
    backrefs: true

- name: Install cpufrequtils
  ansible.builtin.apt:
    name: cpufrequtils
    state: present

- name: Generate cpufrequtils configuration file
  ansible.builtin.template:
    src: cpufrequtils.j2
    dest: /etc/default/cpufrequtils
    owner: root
    group: root
    mode: '0600'
  register: new_config_genereted

- name: Restart service cpufrequtils
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: cpufrequtils
  when: new_config_genereted.changed
    
- name: Update GRUB configuration
  ansible.builtin.command: update-grub
  changed_when: true
  when: new_config_genereted.changed
  notify: "Restart host"
